### PR TITLE
Added support for friendly node names

### PR DESCRIPTION
**Pull request by jpg0**
Friendly node names are useful for auto-configuring UIs

### CODE REVIEW

**Comment by lorenwest** [comment]
The `$name` attribute was introduced in the 3.x version of the [Homie Specification](https://homieiot.github.io/specification/). This library this is an implementation of the 2.x specification, and up until this PR, it has no 3.0 specific functionality.

Adding `$name` won't break the 2.0 spec so this is a reasonable addition, but what are your thoughts on the value of moving this library up to the 3.0 spec?

**Comment by jpg0** [comment]
Sorry, I didn't realise that this was only implementing 2.x, which was also why I created the PR for announcement for node ids!

It looks like 3.x is compatible with 2.x, although I can't find anywhere in the spec that states compatibility.

My personal desire for using homie is to integrate well with Openhab, which has [just released support for homie](https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html#mqtt-thing-auto-discovery), although the 3.x spec. So for me I'm keen on 3.x, and I'd expect the other openhab users to want the same.

I see that whilst the esp8266 implementation doesn't yet support 3.x, [it is being worked on](https://github.com/bodiroga/homie-esp8266/tree/develop-v3), so maybe possible to use this API to retain similarity with that library?

**Comment by lorenwest** [comment]
I've been following the Homie 3.0 spec, and David Graeff of OpenHAB is an active contributor to that spec.

Not sure what feature will motivate me to update this library to full 3.x compatibility - maybe an OpenHAB integration project.

If anyone wants to collaborate I'd be happy to help. Otherwise I'll wait for the 3.x spec to settle down a bit, and implement when I get some time.

**Comment by lorenwest** [comment]
Published these changes today on NPM at version 0.4.0

**Pull request merged**
