### PR TITLE
Swiched nodes from name to id and now publishes node id list

### LINKED ISSUE #3: Doesn't publish node ID list
Should publish the list of nodes, via the $nodes topic. Currently this isn't published.

### PR DESCRIPTION
**Pull request by jpg0**
Fixes #3 
Note that I changed node.name to node.id; I plan to add node.name too, which would be the friendly name.

### CODE REVIEW

**Comment by lorenwest** [comment]
I like this change. Just noticed another PR about a month ago that I want to review before merging, and I haven't looked into the Travis failure. Before merging we have to get to the bottom of the Travis CI failure.

**Comment by jpg0** [comment]
The Travis failure looks like npm is too new for the version of node: https://github.com/npm/npm/issues/20431

**Comment by lorenwest** [comment]
Yep - I just merged another PR that fixes this: https://github.com/microclimates/homie-device/pull/2

So if you can rebase and re-submit the PR I'll merge yours in as well. If you want to add Node10 support in the `.travis.yml` file and it passes the Travis test, that'll be even better!

**Comment by jpg0** [comment]
I just rebased the branch, so all looks good now. I want add support for a couple of other things, so I'll add node10 support with them.

**Comment by lorenwest** [comment]
Perfect - thanks for the contribution!

**Pull request merged**
